## Homework 1 - Disha Gandhi

In [1]:
import numpy as np

#### Question 1

A bank makes four kinds of loans to its customers and these loans yield the following annual interest rates to the bank:

• First mortgage 14%
• Second mortgage 20%
• Home improvement 20%

• Personal overdraft 10%

We are interested in the bank’s lending strategy. The information we know is as following:

1. In total $250 million is lent out.
2. First mortgages are 55% of all mortgages (i.e. first and second mortgage) issued.

3. Second mortgages are 25% of all loans issued.
4. The dollar-weighted average interest rate on all loans is 15%.

Calculate the lending strategy using matrix inversion.  How much is lent in home improvement loans?

In [9]:
A = np.zeros((4,4))
A[0,:] = [1,1,1,1]
A[1,:] = [0.45,-0.55,0,0]
A[2,:] = [0.25,-0.75,0.25,0.25]
A[3,:] = [0.14,0.20,0.20,0.10]
A

array([[ 1.  ,  1.  ,  1.  ,  1.  ],
       [ 0.45, -0.55,  0.  ,  0.  ],
       [ 0.25, -0.75,  0.25,  0.25],
       [ 0.14,  0.2 ,  0.2 ,  0.1 ]])

In [10]:
B = np.zeros((4,1))
B[0,:] = [250]
B[1,:] = [0]
B[2,:] = [0]
B[3,:] = [37.5]
B

array([[250. ],
       [  0. ],
       [  0. ],
       [ 37.5]])

In [11]:
A = np.linalg.inv(A)
np.dot(A,B)

array([[76.38888889],
       [62.5       ],
       [31.94444444],
       [79.16666667]])

#### Question 3

A Lehmer matrix is one whose entries are specified by the following rule

Ai,j = i/j if j > i and Ai,j = j/i otherwise

Write a function named lehmer_entry which takes two arguments and outputs the value of the entry. Then use “for loop(s)” to generate a 20 by 20 Lehmer Matrix.

(Hint: First generate a 4 by 4 matrix with all the elements being 0. Then use for loop(s) and if statement to define the Lehmer matrix. Find the 4 by 4 Lehmer matrix and use the Wikipedia to check. Then you can change the code to run a 20 by 20)

Is A symmetric?

In [25]:
A=np.zeros((20,20))

In [55]:
def lehmer_entry(row,column):
    if column > row:
        value = float(row/column)
    else:
        value = float(column/row)
    return value

In [56]:
x = np.arange(start=0, stop=20, step=1)
y = np.arange(start=0, stop=20, step=1)

for i in x:
    for j in y:
        A[i,j] = lehmer_entry(i+1,j+1)

A

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.5       , 1.        , 0.66666667, 0.5       , 0.4       ,
        0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ,
        0.18181818, 0.16666667, 0.15384615, 0.14285714, 0.13333333,
        0.125     , 0.11764706, 0.11111111, 0.10526316, 0.1       ],
       [0.33333333, 0.66666667, 1.        , 0.75      , 0.6       ,
        0.5       , 0.42857143, 0.375     , 0.33333333, 0.3       ,
        0.27272727, 0.25      , 0.23076923, 0.21428571, 0.2       ,
        0.1875    , 0.17647059, 0.16666667, 0.15789474, 0.15      ],
       [0.25      , 0.5       , 0.75      , 1.        , 0.8       ,
        0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ,
        0.36363636, 0.33333333, 0.30769231, 0

#### Question 4

Going back to the Lehmer matrix problem.

Calculate the inverse of A and assign it to C.

Assign [1 2 3 4 5 6 7 8 9 10 10 9 8 7 6 5 4 3 2 1] to d.

Solve for x in the equation Ax = Cd

What is x10 ? Round to 1 decimal place.  Be careful if the answer you get is in scientific notation.

In [57]:
C = np.linalg.inv(A)
d = [1,2,3,4,5,6,7,8,9,10,10,9,8,7,6,5,4,3,2,1]

#we need to solve for Ax=Cd

rhs=np.dot(C,d)
x=np.dot(np.linalg.inv(A),rhs)

In [58]:
x

array([-9.04641887e-16,  1.09953367e-14,  3.55162340e-15, -7.72606635e-14,
        1.67182015e-13, -2.57851874e-13,  2.80754357e-13, -1.21154758e-13,
       -2.48120301e+01,  2.00642393e+01,  3.58137507e+01, -3.00626280e+01,
       -3.73699569e-04, -2.77204400e-04, -2.09968770e-04, -1.61954093e-04,
       -1.26922825e-04, -1.00877939e-04,  9.50593309e+01, -1.00062903e+02])

In [59]:
round(x[9],1)

20.1